# Generated by Django 2.0.7 on 2018-07-30 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_profile_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='updated',
        ),
    ]
