# Generated by Django 2.0.7 on 2018-07-31 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_profile_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
    ]
